src/Entity/Songs.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OrderBy;
use App\Repository\SongsRepository;

/**
 * @ORM\Entity(repositoryClass=SongsRepository::class)
 */
class Songs
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @OrderBy({"name" = "ASC"})
     */
    private $Name;

    /**
     * @ORM\ManyToOne(targetEntity=Authors::class)
     */
    private $Author;

    /**
     * @ORM\ManyToOne(targetEntity=MusicStyle::class)
     * @OrderBy({"name" = "ASC"})
     */
    private $musicStyle;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Link;

    /**
     * @ORM\ManyToOne(targetEntity=Chords::class)
     */
    private $chordChorus1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $chordChorus1Name;

    /**
     * @ORM\ManyToOne(targetEntity=Chords::class)
     */
    private $chordChorus2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $chordChorus2Name;

    /**
     * @ORM\ManyToOne(targetEntity=Chords::class)
     */
    private $chordChorus3;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $chordChorus3Name;

    /**
     * @ORM\ManyToOne(targetEntity=Chords::class)
     */
    private $chordChorus4;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $chordChorus4Name;

    /**
     * @ORM\ManyToOne(targetEntity=Chords::class)
     */
    private $chordVerse1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $chordVerse1Name;

    /**
     * @ORM\ManyToOne(targetEntity=Chords::class)
     */
    private $chordVerse2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $chordVerse2Name;

    /**
     * @ORM\ManyToOne(targetEntity=Chords::class)
     */
    private $chordVerse3;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $chordVerse3Name;

    /**
     * @ORM\ManyToOne(targetEntity=Chords::class)
     */
    private $chordVerse4;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $chordVerse4Name;

    /**
     * @ORM\ManyToOne(targetEntity=Chords::class)
     */
    private $chordVerse5;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $chordVerse5Name;

    /**
     * @ORM\ManyToOne(targetEntity=Chords::class)
     */
    private $chordVerse6;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $chordverse6Name;

    /**
     * @ORM\ManyToOne(targetEntity=Chords::class)
     */
    private $chordVerse7;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $chordVerse7Name;

    /**
     * @ORM\ManyToOne(targetEntity=Chords::class)
     */
    private $chordVerse8;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $chordVerse8Name;

    /**
     * @ORM\ManyToOne(targetEntity=Chords::class)
     */
    private $chordChorus5;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $chordChorus5Name;

    /**
     * @ORM\ManyToOne(targetEntity=Chords::class)
     */
    private $chordChorus7;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $chordChorus7Name;

    /**
     * @ORM\ManyToOne(targetEntity=Chords::class)
     */
    private $chordChorus8;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $chordChorus8Name;

    /**
     * @ORM\ManyToOne(targetEntity=Chords::class)
     */
    private $chordChorus6;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $chordChorus6Name;

   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getAuthor(): ?Authors
    {
        return $this->Author;
    }

    public function setAuthor(?Authors $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    public function __toString(){
        // to show the name of the Category in the select
        return $this->name;
        // to show the id of the Category in the select
        // return $this->id;
    }

      public function getMusicStyle(): ?MusicStyle
      {
          return $this->musicStyle;
      }

      public function setMusicStyle(?MusicStyle $musicStyle): self
      {
          $this->musicStyle = $musicStyle;

          return $this;
      }

      public function getLink(): ?string
      {
          return $this->Link;
      }

      public function setLink(string $Link): self
      {
          $this->Link = $Link;

          return $this;
      }

      public function getChordChorus1(): ?Chords
      {
          return $this->chordChorus1;
      }

      public function setChordChorus1(?Chords $chordChorus1): self
      {
          $this->chordChorus1 = $chordChorus1;

          return $this;
      }

      public function getChordChorus1Name(): ?string
      {
          return $this->chordChorus1Name;
      }

      public function setChordChorus1Name(?string $chordChorus1Name): self
      {
          $this->chordChorus1Name = $chordChorus1Name;

          return $this;
      }

      public function getChordChorus2(): ?Chords
      {
          return $this->chordChorus2;
      }

      public function setChordChorus2(?Chords $chordChorus2): self
      {
          $this->chordChorus2 = $chordChorus2;

          return $this;
      }

      public function getChordChorus2Name(): ?string
      {
          return $this->chordChorus2Name;
      }

      public function setChordChorus2Name(?string $chordChorus2Name): self
      {
          $this->chordChorus2Name = $chordChorus2Name;

          return $this;
      }

      public function getChordChorus3(): ?Chords
      {
          return $this->chordChorus3;
      }

      public function setChordChorus3(?Chords $chordChorus3): self
      {
          $this->chordChorus3 = $chordChorus3;

          return $this;
      }

      public function getChordChorus3Name(): ?string
      {
          return $this->chordChorus3Name;
      }

      public function setChordChorus3Name(?string $chordChorus3Name): self
      {
          $this->chordChorus3Name = $chordChorus3Name;

          return $this;
      }

      public function getChordChorus4(): ?Chords
      {
          return $this->chordChorus4;
      }

      public function setChordChorus4(?Chords $chordChorus4): self
      {
          $this->chordChorus4 = $chordChorus4;

          return $this;
      }

      public function getChordChorus4Name(): ?string
      {
          return $this->chordChorus4Name;
      }

      public function setChordChorus4Name(?string $chordChorus4Name): self
      {
          $this->chordChorus4Name = $chordChorus4Name;

          return $this;
      }

      public function getChordVerse1(): ?Chords
      {
          return $this->chordVerse1;
      }

      public function setChordVerse1(?Chords $chordVerse1): self
      {
          $this->chordVerse1 = $chordVerse1;

          return $this;
      }

      public function getChordVerse1Name(): ?string
      {
          return $this->chordVerse1Name;
      }

      public function setChordVerse1Name(?string $chordVerse1Name): self
      {
          $this->chordVerse1Name = $chordVerse1Name;

          return $this;
      }

      public function getChordVerse2(): ?Chords
      {
          return $this->chordVerse2;
      }

      public function setChordVerse2(?Chords $chordVerse2): self
      {
          $this->chordVerse2 = $chordVerse2;

          return $this;
      }

      public function getChordVerse2Name(): ?string
      {
          return $this->chordVerse2Name;
      }

      public function setChordVerse2Name(?string $chordVerse2Name): self
      {
          $this->chordVerse2Name = $chordVerse2Name;

          return $this;
      }

      public function getChordVerse3(): ?Chords
      {
          return $this->chordVerse3;
      }

      public function setChordVerse3(?Chords $chordVerse3): self
      {
          $this->chordVerse3 = $chordVerse3;

          return $this;
      }

      public function getChordVerse3Name(): ?string
      {
          return $this->chordVerse3Name;
      }

      public function setChordVerse3Name(?string $chordVerse3Name): self
      {
          $this->chordVerse3Name = $chordVerse3Name;

          return $this;
      }

      public function getChordVerse4(): ?Chords
      {
          return $this->chordVerse4;
      }

      public function setChordVerse4(?Chords $chordVerse4): self
      {
          $this->chordVerse4 = $chordVerse4;

          return $this;
      }

      public function getChordVerse4Name(): ?string
      {
          return $this->chordVerse4Name;
      }

      public function setChordVerse4Name(?string $chordVerse4Name): self
      {
          $this->chordVerse4Name = $chordVerse4Name;

          return $this;
      }

      public function getChordVerse5(): ?Chords
      {
          return $this->chordVerse5;
      }

      public function setChordVerse5(?Chords $chordVerse5): self
      {
          $this->chordVerse5 = $chordVerse5;

          return $this;
      }

      public function getChordVerse5Name(): ?string
      {
          return $this->chordVerse5Name;
      }

      public function setChordVerse5Name(?string $chordVerse5Name): self
      {
          $this->chordVerse5Name = $chordVerse5Name;

          return $this;
      }

src/Controller/SongsController.php
<?php

namespace App\Controller;

use App\Repository\MusicStyleRepository;
use App\Repository\SongsRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class SongsController extends AbstractController 
{   
    /**
     * @var SongsRepository
     */
    private $repository;

    public function __construct(SongsRepository $repository, MusicStyleRepository $musicStyleRepository)
    {
        $this->repository = $repository;
        $this->musicStyleRepository = $musicStyleRepository;
    }

    /**
     * @Route("/chansons", name="songs.index")
     * @return \Symfony\Component\Httmfoundation\Response
     */
    public function index(): Response
    {
       $songs = $this->repository->findBy([], ['Name' => 'ASC']);
       $musicStyle = $this->musicStyleRepository->findAll();
     
        return $this->render('songs.html.twig', [
            'songs' => $songs,
            'musicStyle' => $musicStyle,
        ]);
    }
}

src/Controller/songs/BalladeDeJimController.php
<?php

namespace App\Controller\songs;


use App\Repository\SongsRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class BalladeDeJimController extends AbstractController 
{   

    /**
     * @var SongsRepository
     */
    private $repository;

    public function __construct(SongsRepository $repository)
    {
        $this->repository = $repository;
    }

    
    /**
     * @Route("/balladeDeJim", name="balladeDeJim")
     */
    public function index()
    {
     
        $songs = $this->repository->find(15);

       return $this->render('songs/balladeDeJim.html.twig', compact('songs'));
    }
}

src/Controller/songs/DepuisToujoursController.php
<?php

namespace App\Controller\songs;


use App\Repository\SongsRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class DepuisToujoursController extends AbstractController 
{   

        /**
     * @var SongsRepository
     */
    private $repository;

    public function __construct(SongsRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @Route("/depuistoujours", name="depuisToujours")
     * 
     */
    public function index()
    {
    $songs = $this->repository->find(3);
       return $this->render('songs/depuisToujours.html.twig' , compact('songs') );
    }
}

src/Controller/songs/FilsdefranceController.php
<?php

namespace App\Controller\songs;


use App\Repository\SongsRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class FilsdefranceController extends AbstractController 
{   

    /**
     * @var SongsRepository
     */
    private $repository;

    public function __construct(SongsRepository $repository)
    {
        $this->repository = $repository;
    }

    
    /**
     * @Route("/filsdefrance", name="filsdefrance")
     */
    public function index()
    {
     
        $songs = $this->repository->find(1);

       return $this->render('songs/filsdefrance.html.twig', compact('songs'));
    }
}

src/Controller/songs/FouleSentimentaleController.php
<?php

namespace App\Controller\songs;


use App\Repository\SongsRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class FouleSentimentaleController extends AbstractController 
{   

    /**
    * @var SongsRepository
    */
    private $repository;

    
    public function __construct(SongsRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @Route("/FouleSentimentale", name="FouleSentimentale")
     * 
     */
    public function index()
    {
    $songs = $this->repository->find(6);
       return $this->render('songs/fouleSentimentale.html.twig' , compact('songs') );
    }
}

src/Controller/songs/GreatHeartController.php
<?php

namespace App\Controller\songs;


use App\Repository\SongsRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class GreatHeartController extends AbstractController 
{   


       /**
     * @var SongsRepository
     */
    private $repository;

    public function __construct(SongsRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @Route("/greatHeart", name="greatHeart")
     * 
     */
    public function index()
    {
     
        $songs = $this->repository->find(12);
        return $this->render('songs/greatHeart.html.twig', compact('songs'));
    }
}

src/Controller/songs/ImagineController.php
<?php

namespace App\Controller\songs;


use App\Repository\SongsRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class ImagineController extends AbstractController 
{   


       /**
     * @var SongsRepository
     */
    private $repository;

    public function __construct(SongsRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @Route("/imagine", name="imagine")
     * 
     */
    public function index()
    {
     
        $songs = $this->repository->find(11);
        return $this->render('songs/imagine.html.twig', compact('songs'));
    }
}

src/Controller/songs/JaunéController.php
<?php

namespace App\Controller\songs;


use App\Repository\SongsRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class JaunéController extends AbstractController 
{   

        /**
     * @var SongsRepository
     */
    private $repository;

    public function __construct(SongsRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @Route("/jauné", name="jauné")
     * 
     */
    public function index()
    {
    $songs = $this->repository->find(7);
       return $this->render('songs/jauné.html.twig' , compact('songs') );
    }
}

src/Controller/songs/LaMisereDenFaceController.php
<?php

namespace App\Controller\songs;


use App\Repository\SongsRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class LaMisereDenFaceController extends AbstractController 
{   

    /**
     * @var SongsRepository
     */
    private $repository;

    public function __construct(SongsRepository $repository)
    {
        $this->repository = $repository;
    }

    
    /**
     * @Route("/laMisèreDenFace", name="laMisèreDenFace")
     */
    public function index()
    {
     
        $songs = $this->repository->find(16);

       return $this->render('songs/laMisèreDenFace.html.twig', compact('songs'));
    }
}

src/Controller/songs/LeanOnController.php
<?php

namespace App\Controller\songs;


use App\Repository\SongsRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class LeanOnController extends AbstractController 
{   


       /**
     * @var SongsRepository
     */
    private $repository;

    public function __construct(SongsRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @Route("/leanOn", name="leanOn")
     * 
     */
    public function index()
    {
     
        $songs = $this->repository->find(9);
        return $this->render('songs/leanOn.html.twig', compact('songs'));
    }
}

templates/songs/depuisToujours.html.twig
{% extends 'base.html.twig' %}


{% block body %}
 <div class="v-page-heading v-bg-stylish v-bg-stylish-v1">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="heading-text">
                        <h1 class="entry-title">{{songs.name}} - {{songs.author}}</h1>
                    </div>

                    <ol class="breadcrumb">
                        <li><a href="/">Accueil</a></li>
                        <li class="active"><a href="{{ path('songs.index') }}">Chansons</a></li>
                            <li class="active">{{songs.name}} - {{songs.author}}</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>


<div class="v-page-wrap">

        <div class="container">
            <div class="row">
                <div class="col-sm-12">

                    <article class="portfolio-article">


                         <div class="v-portfolio-item-content clearfix">

                            <div class="row">

                                    <div class="col-sm-8 col-lg-offset-2">
                                        <figure class="media-wrap">
                                            <iframe height="400" src="https://www.youtube.com/embed/ndYUh-CvTik" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                                        </figure>
                                    </div>

                            </div>
                        </div>



                        <div class="related-projects clearfix">

                            <h3 class="v-heading v-center-heading"><span>Refrain</span></h3>

                            <div class="row center">

                                <div class="col-sm-12">
                                    <div class="col-sm-3">

                                        <img src="assets/img/accords/{{songs.chordChorus1}}" style="height: 190px;" />
                                        <span><h5 style="text-align: center;">1 : {{songs.chordChorus1Name}}</h5></span>

                                    </div>

                                    <div class="col-sm-3">

                                        <img src="assets/img/accords/{{songs.chordChorus2}}" style="height: 190px;" />
                                        <span><h5 style="text-align: center;">2 : {{songs.chordChorus2Name}}</h5></span>

                                    </div>

                                    <div class="col-sm-3">

                                        <img src="assets/img/accords/{{songs.chordChorus3}}" style="height: 190px;" />
                                        <span><h5 style="text-align: center;">3 : {{songs.chordChorus3Name}}</h5></span>

                                    </div>

                                    <div class="col-sm-3">

                                        <img src="assets/img/accords/{{songs.chordChorus4}}" style="height: 190px;" />
                                        <span><h5 style="text-align: center;">4 : {{songs.chordChorus4Name}}</h5></span>

                                    </div>



                                     <div class="col-sm-3">

                                        <img src="assets/img/accords/{{songs.chordChorus5}}" style="height: 190px;" />
                                        <span><h5 style="text-align: center;">5 : {{songs.chordChorus5Name}}</h5></span>

                                    </div>

                                    <div class="col-sm-3">

                                        <img src="assets/img/accords/{{songs.chordChorus6}}" style="height: 190px;" />
                                        <span><h5 style="text-align: center;">6 : {{songs.chordChorus6Name}}</h5></span>

                                    </div>

                                    <div class="col-sm-3">

                                        <img src="assets/img/accords/{{songs.chordChorus7}}" style="height: 190px;" />
                                        <span><h5 style="text-align: center;">7 : {{songs.chordChorus7Name}}</h5></span>

                                    </div>

                                    <div class="col-sm-3">

                                        <img src="assets/img/accords/{{songs.chordChorus8}}" style="height: 190px;" />
                                        <span><h5 style="text-align: center;">8 : {{songs.chordChorus8Name}}</h5></span>

                                    </div>
                                    
                                </div>
                                
                            </div>
                        </div>

                    

                        <div class="related-projects clearfix">

                            <h3 class="v-heading v-center-heading"><span>Couplet</span></h3>

                            <div class="row center">

                                <div class="col-sm-12">
                                     <div class="col-sm-3">

                                        <img src="assets/img/accords/{{songs.chordVerse1}}" style="height: 190px;" />
                                        <span><h5 style="text-align: center;">1 : {{songs.chordVerse1Name}}</h5></span>

                                    </div>

                                    <div class="col-sm-3">

                                        <img src="assets/img/accords/{{songs.chordVerse2}}" style="height: 190px;" />
                                        <span><h5 style="text-align: center;">2 : {{songs.chordVerse2Name}}</h5></span>

                                    </div>
                                    
                                </div>
                                
                            </div>
                        </div>

                        <div class="container">
                            <div class="v-spacer col-sm-12 v-height-big"></div>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/songs/filsdefrance.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    <div class="v-page-heading v-bg-stylish v-bg-stylish-v1">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="heading-text">
                        <h1 class="entry-title">{{songs.name}} - {{songs.author}}</h1>
                    </div>

                    <ol class="breadcrumb">
                        <li><a href="/">Accueil</a></li>
                        <li class="active"><a href="{{ path('songs.index') }}">Chansons</a></li>
                            <li class="active">{{songs.name}} - {{songs.author}}</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>


    <div class="v-page-wrap">

        <div class="container">
            <div class="row">
                <div class="col-sm-12">

                    <article class="portfolio-article">

                        <div class="related-projects clearfix">

                            <h3 class="v-heading v-center-heading"><span>Refrain</span></h3>

                            <div class="row center">

                                <div class="col-sm-12">
                                    <div class="col-sm-3">

                                        <img src="assets/img/accords/{{songs.chordChorus1}}" style="height: 190px;" />
                                        <span><h5 style="text-align: center;">1 : {{songs.chordChorus1Name}}</h5></span>

                                    </div>

                                    <div class="col-sm-3">

                                        <img src="assets/img/accords/{{songs.chordChorus2}}" style="height: 190px;" />
                                        <span><h5 style="text-align: center;">1 : {{songs.chordChorus2Name}}</h5></span>

                                    </div>

                                    <div class="col-sm-3">

                                        <img src="assets/img/accords/{{songs.chordChorus3}}" style="height: 190px;" />
                                        <span><h5 style="text-align: center;">1 : {{songs.chordChorus3Name}}</h5></span>

                                    </div>

                                    <div class="col-sm-3">

                                        <img src="assets/img/accords/{{songs.chordChorus4}}" style="height: 190px;" />
                                        <span><h5 style="text-align: center;">1 : {{songs.chordChorus4Name}}</h5></span>

                                    </div>
                                    
                                </div>
                                
                            </div>
                        </div>

                    

                        <div class="related-projects clearfix">

                            <h3 class="v-heading v-center-heading"><span>Couplet</span></h3>

                            <div class="row center">

                                <div class="col-sm-12">
                                     <div class="col-sm-3">

                                        <img src="assets/img/accords/{{songs.chordChorus1}}" style="height: 190px;" />
                                        <span><h5 style="text-align: center;">1 : {{songs.chordChorus1Name}}</h5></span>

                                    </div>

                                    <div class="col-sm-3">

                                        <img src="assets/img/accords/{{songs.chordChorus2}}" style="height: 190px;" />
                                        <span><h5 style="text-align: center;">1 : {{songs.chordChorus2Name}}</h5></span>

                                    </div>

                                    <div class="col-sm-3">

                                        <img src="assets/img/accords/{{songs.chordChorus3}}" style="height: 190px;" />
                                        <span><h5 style="text-align: center;">1 : {{songs.chordChorus3Name}}</h5></span>

                                    </div>

                                    <div class="col-sm-3">

                                        <img src="assets/img/accords/{{songs.chordChorus4}}" style="height: 190px;" />
                                        <span><h5 style="text-align: center;">1 : {{songs.chordChorus4Name}}</h5></span>

                                    </div>
                                    
                                </div>
                                
                            </div>
                        </div>

                        <div class="container">
                            <div class="v-spacer col-sm-12 v-height-big"></div>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </div>




  

{% endblock %}